apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-engine
  template:
    metadata:
      labels:
        app: ai-engine
    spec:
      containers:
      - name: ai-engine
        image: bacdocker/ai-engine:v13
        ports:
        - containerPort: 8000
        env:
        - name: OLLAMA_MODEL
          value: llama3.1:8b
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"