apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-app
  labels:
    app: stress-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress-app
  template:
    metadata:
      labels:
        app: stress-app
    spec:
      containers:
      - name: stress-app
        image: bacdocker/aiops-stress-app:v2
        ports:
        - containerPort: 5001