apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: aiops-alert-rules
  namespace: monitoring
  labels:
    release: monitoring

spec:
  groups:
  - name: aiops.rules
    rules:

    - alert: HighPodCPUUsage
      expr: sum(rate(container_cpu_usage_seconds_total{namespace="default"}[2m])) by (namespace, pod) > 0.8
      for: 10s
      labels:
        severity: warning
      annotations:
        summary: "High CPU usage detected"
        description: "Pod CPU usage above 80%"

    - alert: HighMemoryUsage
      expr: sum(container_memory_working_set_bytes{namespace="default"}) by (pod) > 500000000
      for: 30s
      labels:
        severity: warning
      annotations:
        summary: "High Memory Usage"
        description: "Pod memory usage above threshold"

    - alert: PodCrashLoop
      expr: increase(kube_pod_container_status_restarts_total{namespace="default"}[5m]) > 3
      for: 30s
      labels:
        severity: critical
      annotations:
        summary: "Pod Crash Loop"
        description: "Container restarting repeatedly"

    - alert: PodCrashLoopBackOff
      expr: max_over_time(kube_pod_container_status_waiting_reason{namespace="default",reason="CrashLoopBackOff"}[5m]) >= 1
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "Pod CrashLoopBackOff"
        description: "Container is in CrashLoopBackOff waiting state"

    - alert: PodOOMKilled
      expr: kube_pod_container_status_last_terminated_reason{namespace="default",reason="OOMKilled"} == 1
      for: 30s
      labels:
        severity: critical
      annotations:
        summary: "Pod OOMKilled"
        description: "Container killed due to memory exhaustion"

    - alert: PodImagePullBackOff
      expr: max_over_time(kube_pod_container_status_waiting_reason{namespace="default",reason="ImagePullBackOff"}[5m]) >= 1
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "Pod ImagePullBackOff"
        description: "Container image pull backoff detected"

    - alert: PodImagePullBackOffPersistent
      expr: |
        min_over_time(kube_pod_container_status_waiting_reason{namespace="default",reason="ImagePullBackOff"}[15m]) >= 1
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "Pod ImagePullBackOff Persistent"
        description: "Image pull backoff has remained continuously active for an extended duration"

    - alert: PodErrImagePull
      expr: max_over_time(kube_pod_container_status_waiting_reason{namespace="default",reason="ErrImagePull"}[5m]) >= 1
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "Pod ErrImagePull"
        description: "Container image pull error detected"

    - alert: PodCreateContainerConfigError
      expr: max_over_time(kube_pod_container_status_waiting_reason{namespace="default",reason="CreateContainerConfigError"}[5m]) >= 1
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "Pod CreateContainerConfigError"
        description: "Container configuration error detected"

    - alert: PodNotReadyTooLong
      expr: min_over_time(kube_pod_status_ready{namespace="default",condition="true"}[10m]) == 0
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "Pod Not Ready Too Long"
        description: "Pod has remained not ready for an extended period"